<?php 
    echo"<footer>
            <section class='ft-main'>
                <div class='ft-main-item'>
                    <h2 class='ft-title'>Navigate</h2>
                    <ul>
                        <li><a href='index.php'>Home</a></li>
                        <li><a href='contribute.php'>Contribute</a></li>
                        <li><a href='enquiry.php'>Enquiry</a></li>
                    </ul>
                </div>
                <div class='ft-main-item'>
                    <h2 class='ft-title'>Resources</h2>
                    <ul>
                        <li><a href='care.php'>Care</a></li>
                        <li><a href='tools.php'>Tools</a></li>
                        <li><a href='tutorial.php'>Tutorial</a></li>
                    </ul>
                </div>
                <div class='ft-main-item'>
                    <h2 class='ft-title'>Classification</h2>
                    <ul>
                        <li><a href='classify.php#family'>Family</a></li>
                        <li><a href='classify.php#genus'>Genus</a></li>
                        <li><a href='classify.php#species'>Species</a></li>
                    </ul>
                </div>
                <div class='ft-main-item'>
                    <h2 class='ft-title'>Identify</h2>
                    <ul>
                        <li><a href='identify.php#identify_form'>Upload Image</a></li>
                        <li><a href='identify.php#identify_ways'>Identify Ways</a></li>
                        <li><a href='identify.php#tools'>Indentify Tools</a></li>
                    </ul>
                </div>
                <div class='ft-main-item'>
                    <h2 class='ft-title'>About Us</h2>
                    <ul>
                        <li><a href='index.php#team'>The Team</a></li>
                        <li><a href='mailto:104386364@students.swinburne.edu.my'>Contact us</a></li>
                        <li><a href='https://github.com/Miyuki32/herbaria-webstie'>Our Github</a></li>
                    </ul>
                </div>
                <div class='ft-main-item'>
                    <h2 class='ft-title'>More Info</h2>
                    <ul>
                        <li><a href='acknowledgement.php'>Acknowledgement</a></li>
                        <li><a href='enhancement1.php'>Enhancements</a></li>
                    </ul>
                </div>
            </section>
            <p class='ft-copy'>
                &copy; 2024 DaFwiedPotato. All rights reserved.
            </p>
        </footer>"
?>